var easyGames = [
    [
        [1, 2, 6, null, null, 7, null, null, null],
        [null, null, 3, null, 8, null, null, null, 5],
        [5, null, 8, null, 9, null, null, 3, null],
        [6, null, 4, 8, 7, null, 5, null, 2],
        [null, null, 5, null, null, null, 8, null, null],
        [2, null, 9, null, 5, 3, 1, null, 6],
        [null, 6, null, null, 4, null, 3, null, 1],
        [3, null, null, null, 2, null, 9, null, null],
        [null, null, null, 3, null, null, 7, 5, 8],
    ],
    [
        [8, 5, null, 9, 4, null, null, null, 7],
        [1, null, null, null, null, null, 8, null, null],
        [null, 2, null, 8, 1, null, null, 3, null],
        [null, null, 6, null, null, null, 4, 9, null],
        [4, null, null, 3, 9, 8, null, null, 5],
        [null, 9, 1, null, null, null, 7, null, null],
        [null, 1, null, null, 3, 7, null, 4, null],
        [null, null, 5, null, null, null, null, null, 6],
        [6, null, null, null, 5, 4, null, 7, 1],
    ],
    [
        [null, null, 9, null, 7, null, null, 8, null],
        [6, 4, null, null, 1, 2, null, null, null],
        [null, null, null, 5, 9, 4, 6, null, 1],
        [8, null, 7, 1, null, null, 3, null, null],
        [null, null, 2, 4, null, 6, 7, null, null],
        [null, null, 6, null, null, 8, 2, null, 9],
        [5, null, 8, 9, 6, 1, null, null, null],
        [null, null, null, 2, 4, null, null, 9, 7],
        [null, 2, null, null, 8, null, 1, null, null],
    ],
    [
        [null, 1, 8, 2, null, 5, null, 4, null],
        [null, null, 3, null, 8, null, null, null, null],
        [7, 2, null, 4, null, 3, null, null, 1],
        [null, 3, 6, null, null, null, null, 1, null],
        [9, null, null, 6, null, 7, null, null, 4],
        [null, 7, null, null, null, null, 5, 8, null],
        [1, null, null, 3, null, 8, null, 6, 5],
        [null, null, null, null, 7, null, 1, null, null],
        [null, 6, null, 9, null, 4, 3, 7, null]
    ],
    [
        [null, 7, null, null, null, null, null, null, 9],
        [5, 1, null, 4, 2, null, 6, null, null],
        [null, 8, null, 3, null, null, 7, null, null],
        [null, null, 8, null, null, 1, 3, 7, null],
        [null, 2, 3, null, 8, null, null, 4, null],
        [4, null, null, 9, null, null, 1, null, null],
        [9, 6, 2, 8, null, null, null, 3, null],
        [null, null, null, null, 1, null, 4, null, null],
        [7, null, null, 2, null, 3, null, 9, 6],
    ]
];

// [
//     [],
//     [],
//     [],
//     [],
//     [],
//     [],
//     [],
//     [],
//     [],
// ]

var easyGame4Solved = [
    [3, 7, 4, 1, 6, 8, 2, 5, 9],
    [5, 1, 9, 4, 2, 7, 6, 8, 3],
    [2, 8, 6, 3, 9, 5, 7, 1, 4],
    [6, 9, 8, 5, 4, 1, 3, 7, 2],
    [1, 2, 3, 7, 8, 6, 9, 4, 5],
    [4, 5, 7, 9, 3, 2, 1, 6, 8],
    [9, 6, 2, 8, 7, 4, 5, 3, 1],
    [8, 3, 5, 6, 1, 9, 4, 2, 7],
    [7, 4, 1, 2, 5, 3, 8, 9, 6],
];